//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.30 at 05:21:08 PM MESZ 
//


package net.ee.pfanalyzer.model.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseElementType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BaseElementType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="bus"/>
 *     &lt;enumeration value="branch"/>
 *     &lt;enumeration value="generator"/>
 *     &lt;enumeration value="custom"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BaseElementType")
@XmlEnum
public enum BaseElementType {

    @XmlEnumValue("bus")
    BUS("bus"),
    @XmlEnumValue("branch")
    BRANCH("branch"),
    @XmlEnumValue("generator")
    GENERATOR("generator"),
    @XmlEnumValue("custom")
    CUSTOM("custom");
    private final String value;

    BaseElementType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BaseElementType fromValue(String v) {
        for (BaseElementType c: BaseElementType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
