//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.07 at 05:22:25 PM MEZ 
//


package net.ee.pfanalyzer.model.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkParameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkParameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="option" type="{http://www.mehg.net/schema/PowerFlowAnalyzer}NetworkParameterValueOption" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="display" type="{http://www.mehg.net/schema/PowerFlowAnalyzer}NetworkParameterValueDisplay" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="purpose" type="{http://www.mehg.net/schema/PowerFlowAnalyzer}NetworkParameterPurposeRestriction" default="parameter" />
 *       &lt;attribute name="inherit" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="empty" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="restriction" type="{http://www.mehg.net/schema/PowerFlowAnalyzer}NetworkParameterValueRestriction" default="none" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.mehg.net/schema/PowerFlowAnalyzer}NetworkParameterType" />
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkParameter", propOrder = {
    "option",
    "display"
})
public class NetworkParameter {

    protected List<NetworkParameterValueOption> option;
    protected NetworkParameterValueDisplay display;
    @XmlAttribute
    protected NetworkParameterPurposeRestriction purpose;
    @XmlAttribute
    protected Boolean inherit;
    @XmlAttribute
    protected Boolean empty;
    @XmlAttribute
    protected String value;
    @XmlAttribute
    protected String defaultValue;
    @XmlAttribute
    protected NetworkParameterValueRestriction restriction;
    @XmlAttribute
    protected String description;
    @XmlAttribute
    protected String label;
    @XmlAttribute
    protected NetworkParameterType type;
    @XmlAttribute(name = "ID", required = true)
    protected String id;

    /**
     * Gets the value of the option property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the option property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkParameterValueOption }
     * 
     * 
     */
    public List<NetworkParameterValueOption> getOption() {
        if (option == null) {
            option = new ArrayList<NetworkParameterValueOption>();
        }
        return this.option;
    }

    /**
     * Gets the value of the display property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkParameterValueDisplay }
     *     
     */
    public NetworkParameterValueDisplay getDisplay() {
        return display;
    }

    /**
     * Sets the value of the display property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkParameterValueDisplay }
     *     
     */
    public void setDisplay(NetworkParameterValueDisplay value) {
        this.display = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkParameterPurposeRestriction }
     *     
     */
    public NetworkParameterPurposeRestriction getPurpose() {
        if (purpose == null) {
            return NetworkParameterPurposeRestriction.PARAMETER;
        } else {
            return purpose;
        }
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkParameterPurposeRestriction }
     *     
     */
    public void setPurpose(NetworkParameterPurposeRestriction value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the inherit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isInherit() {
        if (inherit == null) {
            return true;
        } else {
            return inherit;
        }
    }

    /**
     * Sets the value of the inherit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInherit(Boolean value) {
        this.inherit = value;
    }

    /**
     * Gets the value of the empty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEmpty() {
        if (empty == null) {
            return false;
        } else {
            return empty;
        }
    }

    /**
     * Sets the value of the empty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEmpty(Boolean value) {
        this.empty = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the restriction property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkParameterValueRestriction }
     *     
     */
    public NetworkParameterValueRestriction getRestriction() {
        if (restriction == null) {
            return NetworkParameterValueRestriction.NONE;
        } else {
            return restriction;
        }
    }

    /**
     * Sets the value of the restriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkParameterValueRestriction }
     *     
     */
    public void setRestriction(NetworkParameterValueRestriction value) {
        this.restriction = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkParameterType }
     *     
     */
    public NetworkParameterType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkParameterType }
     *     
     */
    public void setType(NetworkParameterType value) {
        this.type = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
