//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.12 at 03:05:38 PM MEZ 
//


package net.ee.pfanalyzer.model.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkParameterValueRestriction.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NetworkParameterValueRestriction">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="bus-number"/>
 *     &lt;enumeration value="list"/>
 *     &lt;enumeration value="unique parameter value"/>
 *     &lt;enumeration value="existing parameter value"/>
 *     &lt;enumeration value="model ID"/>
 *     &lt;enumeration value="model or class ID"/>
 *     &lt;enumeration value="color (RGB)"/>
 *     &lt;enumeration value="file"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NetworkParameterValueRestriction")
@XmlEnum
public enum NetworkParameterValueRestriction {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("bus-number")
    BUS_NUMBER("bus-number"),
    @XmlEnumValue("list")
    LIST("list"),
    @XmlEnumValue("unique parameter value")
    UNIQUE_PARAMETER_VALUE("unique parameter value"),
    @XmlEnumValue("existing parameter value")
    EXISTING_PARAMETER_VALUE("existing parameter value"),
    @XmlEnumValue("model ID")
    MODEL_ID("model ID"),
    @XmlEnumValue("model or class ID")
    MODEL_OR_CLASS_ID("model or class ID"),
    @XmlEnumValue("color (RGB)")
    COLOR_RGB("color (RGB)"),
    @XmlEnumValue("file")
    FILE("file");
    private final String value;

    NetworkParameterValueRestriction(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NetworkParameterValueRestriction fromValue(String v) {
        for (NetworkParameterValueRestriction c: NetworkParameterValueRestriction.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
