/*******************************************************************************
 * Copyright 2019 Markus Gronau
 * 
 * This file is part of PowerFlowAnalyzer.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:50:27 PM MEZ 
//


package net.ee.pfanalyzer.model.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ee.pfanalyzer.model.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PowerFlowCase_QNAME = new QName("http://www.mehg.net/schema/PowerFlowAnalyzer", "power_flow_case");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ee.pfanalyzer.model.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NetworkParameter }
     * 
     */
    public NetworkParameter createNetworkParameter() {
        return new NetworkParameter();
    }

    /**
     * Create an instance of {@link ModelClassData }
     * 
     */
    public ModelClassData createModelClassData() {
        return new ModelClassData();
    }

    /**
     * Create an instance of {@link AbstractNetworkElementData }
     * 
     */
    public AbstractNetworkElementData createAbstractNetworkElementData() {
        return new AbstractNetworkElementData();
    }

    /**
     * Create an instance of {@link NetworkParameterValueDisplay }
     * 
     */
    public NetworkParameterValueDisplay createNetworkParameterValueDisplay() {
        return new NetworkParameterValueDisplay();
    }

    /**
     * Create an instance of {@link NetworkData }
     * 
     */
    public NetworkData createNetworkData() {
        return new NetworkData();
    }

    /**
     * Create an instance of {@link CaseData }
     * 
     */
    public CaseData createCaseData() {
        return new CaseData();
    }

    /**
     * Create an instance of {@link ModelDBData }
     * 
     */
    public ModelDBData createModelDBData() {
        return new ModelDBData();
    }

    /**
     * Create an instance of {@link DataViewerData }
     * 
     */
    public DataViewerData createDataViewerData() {
        return new DataViewerData();
    }

    /**
     * Create an instance of {@link DataViewerDialogData }
     * 
     */
    public DataViewerDialogData createDataViewerDialogData() {
        return new DataViewerDialogData();
    }

    /**
     * Create an instance of {@link NetworkParameterValueOption }
     * 
     */
    public NetworkParameterValueOption createNetworkParameterValueOption() {
        return new NetworkParameterValueOption();
    }

    /**
     * Create an instance of {@link ModelData }
     * 
     */
    public ModelData createModelData() {
        return new ModelData();
    }

    /**
     * Create an instance of {@link NetworkFlagData }
     * 
     */
    public NetworkFlagData createNetworkFlagData() {
        return new NetworkFlagData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaseData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mehg.net/schema/PowerFlowAnalyzer", name = "power_flow_case")
    public JAXBElement<CaseData> createPowerFlowCase(CaseData value) {
        return new JAXBElement<CaseData>(_PowerFlowCase_QNAME, CaseData.class, null, value);
    }

}
