//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.20 at 01:46:45 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mehg.net/schema/PowerFlowAnalyzer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.ee.pfanalyzer.model.data;
